# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Cart.create(item_count: 0, total_price: 0)
Cart.create(item_count: 0, total_price: 0)

Item.create(name: "Monstera", description: "Nicknamed the “swiss cheese plant”, the Monstera deliciosa is famous for its quirky natural leaf holes. Your Monstera can grow just about anywhere in your home! It tolerates low light, but grows faster and becomes more dramatic in a bright spot. That said, avoid strong, direct sunlight because it may burn the leaves.", price: 30.00, cart_id: 1 , image_link: "https://bloomscape.com/wp-content/uploads/2020/08/bloomscape_monstera_alt_stone.jpg?ver=279417")
Item.create(name: "Fiddle Leaf Fig", description: "The Fiddle Leaf Fig is famous for its broad, vibrant green leaves with prominent veining. It prefers a stable environment and can be fickle when temps fluctuate. Your Fiddle Leaf Fig will grow best with consistent, bright, filtered light. Turn the plant every few months once it begins to lean towards the light. It will prefer an east-facing, sunny window as afternoon sun from a south or west facing window will be too strong and will burn the leaves.", price: 25.00, cart_id: 1 , image_link: "https://bloomscape.com/wp-content/uploads/2020/08/bloomscape_fiddle-leaf-fig_charcoal.jpg?ver=279577")
Item.create(name: "Snake Plant Laurentii", description: "The Snake Plant Laurentii is a succulent plant characterized by its upright swordlike leaves with vibrant yellow edges. Your Laurentii will do best in moderate to bright indirect light. However, it will adapt to low light areas and can also withstand full sun.", price: 20.00, cart_id: 1 , image_link: "https://cdn.shopify.com/s/files/1/0150/6262/products/the-sill_snake-plant-laurentii_variant_medium_hyde_cream_1200x.jpg?v=1620326951")

Item.create(name: "Money Tree", description: "Easy and graceful, with large leaves and a braided trunk. Position your Money Tree in medium to bright indirect light, turning it every time you water it for even growth and leaf development. This plant will also adapt and do well under fluorescent lights.", price: 40.00, cart_id: 1 , image_link: "https://bloomscape.com/wp-content/uploads/2020/12/bloomscape_money-tree_stone-resize.jpg?ver=372952")
Item.create(name: "Bromeliad Pineapple", description: "Truly unique pineapple plant with long-lasting blooms. Your Bromeliad prefers medium to bright indirect light. Insufficient light will cause growth to slow.", price: 23.00, cart_id: 1 , image_link: "https://bloomscape.com/wp-content/uploads/2020/08/bloomscape_bromeliad-pineapple_charcoal-324x389.jpg?ver=279190")
Item.create(name: "Parlor Palm", description: "Easy and graceful, with lush dark green fronds. Parlor Palms are considered low-light palms, but that doesn’t mean “no-light”. They prefer bright filtered light but will adjust to low light areas.", price: 32.00, cart_id: 1 , image_link: "https://bloomscape.com/wp-content/uploads/2020/08/bloomscape_parlor-palmloomscape_slate-324x389.jpg?ver=279264")

Item.create(name: "Staggered Yucca Cane", description: "Low maintenance with sword-like green leaves atop three sturdy canes. Your Yucca Cane will do best in bright indirect light. If the Yucca is exposed to direct light, the leaves may burn. It can tolerate lower light areas but will grow much slower.", price: 50.00, cart_id: 1 , image_link: "https://bloomscape.com/wp-content/uploads/2021/03/bloomscape_yucca-cane_xl_slate.jpg?ver=437485")
Item.create(name: "Prickly Pear Cactus", description: "Playful cactus with low-maintenance care. Place your potted Prickly Pear Cactus on a southeast or west-facing window sill that receives full, direct sunlight in the spring through fall.  In the winter, find a bright indirect sunny area. Transition your Prickly Pear Cactus to the direct light in small increments in the early spring.", price: 35.00, cart_id: 1 , image_link: "https://bloomscape.com/wp-content/uploads/2020/08/bloomscape_prickly-pear-cactus_indigo.jpg?ver=279307")
Item.create(name: "Golden Barrel Cactus", description: "Round, ball-shaped cactus with low-maintenance care. Your Golden Barrel Cactus needs as much sunlight as it can possibly get through the early spring and into late Fall. It can handle indirect sunlight but will thrive in full sun.", price: 33.00, cart_id: 1 , image_link: "https://bloomscape.com/wp-content/uploads/2021/03/bloomscape_golden-barrel-cactus_medium_clay-ALT-scaled.jpg?ver=474335")